apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-nautobot-argo-app
  namespace: streamlit-nautobot-argo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-nautobot-argo-app
  template:
    metadata:
      labels:
        app: streamlit-nautobot-argo-app
    spec:
      containers:
        - name: streamlit
          image: ghcr.io/leothelyon17/streamlit-nautobot-argo-app:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
