apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: ClusterIP  # or NodePort, depending on your cluster/environment
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: streamlit-app
